# Generated by Django 5.1.6 on 2025-04-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='img_url',
            field=models.ImageField(default='https://via.placeholder.com/150', upload_to=''),
            preserve_default=False,
        ),
    ]
